INSERT INTO ITEM(NAME,  CUSTOM_CODE, MMK_CODE, DESCRIPTION, UNIT, QUANTITY_PER_UNIT, MIN_UNITS, MEDIUM_UNITS, MANY_UNITS)
VALUES ('ZB-01',  '12345', '54321', 'Кнопка 1NO', 'Коробка', 5, 2, 4, 10);
SET @item_id=identity();
INSERT INTO ITEM(NAME, CUSTOM_CODE, MMK_CODE, DESCRIPTION, UNIT, QUANTITY_PER_UNIT, MIN_UNITS, MEDIUM_UNITS, MANY_UNITS)
VALUES ('ZB-01', '12345', '54321', 'Кнопка 1NO', 'Коробка', 5, 2, 4, identity());